version: '3'
services:
  www:
    image: chromerce-php
    volumes:
      - "./:/var/www/html"
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 80:80
      - 443:443
    links:
      - db
  db:
    image: chromerce-db
    environment:
      MYSQL_DATABASE: chromerce
      MYSQL_USER: chromerce
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
      - www
    ports:
      - 8001:80
    environment:
      UPLOAD_LIMIT: "64M"
      PMA_HOST: "db"
      PMA_PORT: "3306"    
  jenkins:
    image: jenkins/jenkins
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - ./:/var/jenkins_home      
volumes:
  mysql_data:
